document.addEventListener('DOMContentLoaded', () => {
    const keywordInput = document.getElementById('keyword-input');
    const btnGenerate = document.getElementById('btn-generate');
    const btnDownload = document.getElementById('btn-download');
    const previewStatus = document.getElementById('preview-status');
    const controls = document.getElementById('action-controls');
    const statTheme = document.getElementById('stat-theme');
    const statHash = document.getElementById('stat-hash');

    let currentConfig = null;
    let engineInstance = null;

    // --- Core Generator Logic ---

    function stringToSeed(str) {
        let hash = 0;
        for (let i = 0; i < str.length; i++) {
            const char = str.charCodeAt(i);
            hash = ((hash << 5) - hash) + char;
            hash = hash & hash; // Convert to 32bit integer
        }
        return Math.abs(hash);
    }

    // Pseudo-random number generator based on seed
    function seededRandom(seed) {
        const x = Math.sin(seed++) * 10000;
        return x - Math.floor(x);
    }

    function generatePalette(seed) {
        const hue1 = Math.floor(seededRandom(seed) * 360);
        const hue2 = (hue1 + 180) % 360; // Complementary
        const hue3 = (hue1 + 40) % 360;  // Analogous

        return {
            background: `hsl(${hue1}, 20%, 10%)`,
            playerColor: `hsl(${hue3}, 80%, 60%)`,
            obstacleColor: `hsl(${hue2}, 70%, 50%)`,
            accentColor: `hsl(${hue3}, 100%, 70%)`
        };
    }

    function generateSprite(seed) {
        // Generate 8x8 pixel art (symmetrical)
        const grid = new Array(64).fill(0);
        
        for (let y = 0; y < 8; y++) {
            for (let x = 0; x < 4; x++) { // Left half
                const val = seededRandom(seed + y * 10 + x) > 0.5 ? 1 : 0;
                grid[y * 8 + x] = val;
                grid[y * 8 + (7 - x)] = val; // Mirror to right
            }
        }
        return grid;
    }

    function generateGameConfig(keyword) {
        const seed = stringToSeed(keyword);
        const palette = generatePalette(seed);
        
        // Generate distinct sprites for player and obstacle
        const playerSprite = generateSprite(seed);
        const obstacleSprite = generateSprite(seed + 100);

        return {
            keyword: keyword,
            seed: seed,
            theme: palette,
            sprites: {
                player: playerSprite,
                obstacle: obstacleSprite
            },
            autoPlay: true // Default for preview
        };
    }

    // --- UI Interactions ---

    btnGenerate.addEventListener('click', () => {
        const keyword = keywordInput.value.trim();
        if (!keyword) return;

        // UI Feedback
        previewStatus.innerText = "GENERATING ASSETS...";
        previewStatus.style.color = "#ffbd2e";
        
        // Simulate processing delay for effect
        setTimeout(() => {
            currentConfig = generateGameConfig(keyword);
            
            // Update Stats
            statTheme.innerText = currentConfig.theme.accentColor;
            statTheme.style.color = currentConfig.theme.accentColor;
            statHash.innerText = `0x${currentConfig.seed.toString(16).toUpperCase()}`;
            
            // Init Game
            if (engineInstance) {
                // Ideally we'd destroy the old instance, but replacing innerHTML does the trick mostly
            }
            
            engineInstance = new LoadiEngine('game-container', currentConfig);
            
            previewStatus.innerText = "SYSTEM ACTIVE - AUTO PILOT";
            previewStatus.style.color = "#27c93f";
            controls.classList.remove('hidden');

        }, 800);
    });

    btnDownload.addEventListener('click', () => {
        if (!currentConfig) return;
        createZipPackage(currentConfig);
    });

    // --- ZIP Packaging ---

    async function createZipPackage(config) {
        const zip = new JSZip();
        
        // 1. Get Engine Code
        const response = await fetch('loadi-engine.js');
        const engineCode = await response.text();

        // 2. Create Config File
        // Remove autoPlay for the production version
        const prodConfig = JSON.parse(JSON.stringify(config));
        prodConfig.autoPlay = false;
        
        const configCode = `
            // Generated by Loadi Gen
            // Keyword: ${config.keyword}
            window.loadiConfig = ${JSON.stringify(prodConfig, null, 4)};
        `;

        // 3. Create HTML Wrapper
        const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loadi Game: ${config.keyword}</title>
    <style>
        body { margin: 0; display: flex; justify-content: center; align-items: center; height: 100vh; background: #111; }
        #game-target { width: 100%; max-width: 600px; height: 200px; border: 2px solid ${config.theme.accentColor}; }
    </style>
</head>
<body>
    <div id="game-target"></div>
    
    <script>${configCode}</script>
    <script>${engineCode}</script>
    <script>
        // Initialize Game
        new LoadiEngine('game-target', window.loadiConfig);
    </script>
</body>
</html>
        `;

        zip.file("index.html", htmlContent);
        zip.file("loadi-engine.js", engineCode);
        zip.file("config.js", configCode);

        // Generate Blob
        const content = await zip.generateAsync({ type: "blob" });
        saveAs(content, `loadi-${config.keyword.toLowerCase()}.zip`);
    }

    // Allow Enter key
    keywordInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') btnGenerate.click();
    });
});
